sonar.projectKey=subuvirat_devops-go
sonar.organization=subuvirat

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out