# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Unit tests and coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: go-coverage
        path: coverage.out
  
  code-quality:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Download coverage
      uses: actions/download-artifact@v4
      with:
        name: go-coverage

    - name: SonarQube Cloud Scan
      uses: SonarSource/sonarqube-scan-action@v8.3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR }}
      with:
        args: >
          -Dsonar.qualitygate.wait=true
  
  
  push:
    runs-on: ubuntu-latest
    needs: code-quality

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: "50dfd0cf-78bb-4abf-bf64-4e9f80c7956f"
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get ACR access token
        id: acr-token
        env:
          ACR_NAME: ${{ vars.ACR_NAME }}
        shell: bash
        run: |
          ACR_TOKEN=$(az acr login \
            --name "$ACR_NAME" \
            --expose-token \
            --output tsv \
            --query accessToken)

          echo "::add-mask::$ACR_TOKEN"
          echo "token=$ACR_TOKEN" >> "$GITHUB_OUTPUT"

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ steps.acr-token.outputs.token }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.ACR_NAME }}.azurecr.io/go-web:${{ github.sha }}
            ${{ vars.ACR_NAME }}.azurecr.io/go-web:${{ github.run_id }}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "subash.jaishankar@gmail.com"
        git config --global user.name "subash-bj"
        git add helm/go-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push

